const PDFDocument = require("pdfkit");

function generatePDF(report) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: "A4",
      });

      const buffers = [];

      doc.on("data", (chunk) => buffers.push(chunk));

      doc.on("end", () => {
        resolve(Buffer.concat(buffers));
      });

      // ==========================
      // Title
      // ==========================
      doc
        .fontSize(22)
        .text("AI Autonomous Database Monitoring Report", {
          align: "center",
        });

      doc.moveDown();

      doc
        .fontSize(10)
        .text(`Generated At: ${new Date().toLocaleString()}`);

      doc.moveDown();

      // ==========================
      // Database
      // ==========================
      doc
        .fontSize(16)
        .text("Database Information", {
          underline: true,
        });

      doc.moveDown(0.5);

      doc.fontSize(12);
      doc.text(`Database Name: ${report.database.name}`);
      doc.text(`Version: ${report.database.version}`);
      doc.text(`Database Size: ${report.database.size}`);
      doc.text(`Active Connections: ${report.database.activeConnections}`);

      doc.moveDown();

      // ==========================
      // Monitoring
      // ==========================
      doc
        .fontSize(16)
        .text("Monitoring Summary", {
          underline: true,
        });

      doc.moveDown(0.5);

      doc.fontSize(12);
      doc.text(`Running Queries: ${report.monitoring.runningQueries}`);
      doc.text(`Slow Queries: ${report.monitoring.slowQueries}`);
      doc.text(`Idle Sessions: ${report.monitoring.idleSessions}`);
      doc.text(`Long Transactions: ${report.monitoring.longTransactions}`);
      doc.text(`Locks: ${report.monitoring.locks}`);

      doc.moveDown();

      // ==========================
      // Statistics
      // ==========================
      doc
        .fontSize(16)
        .text("Database Statistics", {
          underline: true,
        });

      doc.moveDown(0.5);

      doc.fontSize(12);
      doc.text(`Commits: ${report.statistics.commits}`);
      doc.text(`Rollbacks: ${report.statistics.rollbacks}`);
      doc.text(`Deadlocks: ${report.statistics.deadlocks}`);

      doc.moveDown();

      // ==========================
      // AI Recommendation
      // ==========================
      doc
        .fontSize(16)
        .text("AI Recommendation", {
          underline: true,
        });

      doc.moveDown(0.5);

      doc.fontSize(12);

      if (
        report.monitoring.runningQueries === 0 &&
        report.monitoring.slowQueries === 0 &&
        report.monitoring.locks === 0 &&
        report.statistics.deadlocks === 0
      ) {
        doc.text(
          "Database is healthy. Continue regular monitoring."
        );
      } else {
        doc.text(
          "Performance issues detected. Review monitoring metrics and optimize database."
        );
      }

      doc.moveDown(2);

      doc
        .fontSize(10)
        .fillColor("gray")
        .text(
          "Generated by AI Autonomous Database Monitoring Platform",
          {
            align: "center",
          }
        );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = {
  generatePDF,
};