const { getOwnedDatabase } = require("./monitoringService");
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

function okResult(body) {
  return {
    statusCode: 200,
    body,
  };
}

function notFoundResult() {
  return {
    statusCode: 404,
    body: {
      success: false,
      message: "Database Not Found",
    },
  };
}

/*
 * Convert PostgreSQL database size such as:
 *
 * "8430 kB"
 * "8 MB"
 * "1 GB"
 *
 * into MB.
 */
function parseDatabaseSize(size) {
  if (!size) return 0;

  const value = parseFloat(String(size));

  if (Number.isNaN(value)) return 0;

  const text = String(size).toLowerCase();

  if (text.includes("gb")) {
    return value * 1024;
  }

  if (text.includes("mb")) {
    return value;
  }

  if (text.includes("kb")) {
    return value / 1024;
  }

  return value;
}

/*
 * Calculate average of a monitoring field.
 */
function average(records, field) {
  if (!records.length) return 0;

  const total = records.reduce(
    (sum, record) => sum + Number(record[field] || 0),
    0
  );

  return total / records.length;
}

/*
 * Calculate maximum of a monitoring field.
 */
function maximum(records, field) {
  if (!records.length) return 0;

  return Math.max(
    ...records.map((record) =>
      Number(record[field] || 0)
    )
  );
}

/*
 * Predict future database failure risk using
 * REAL historical monitoring data.
 */
async function predictDatabaseFailureService(
  databaseId,
  userId
) {
  const database = await getOwnedDatabase(
    databaseId,
    userId
  );

  if (!database) {
    return notFoundResult();
  }

  /*
   * Get recent historical monitoring records.
   *
   * These are the same records that are already
   * being generated by MonitoringWorker.
   */
  const history = await prisma.monitoringMetric.findMany({
    where: {
      databaseId: databaseId,
    },
    orderBy: {
      timestamp: "desc",
    },
    take: 50,
  });

  if (!history.length) {
    return okResult({
      success: true,
      database: database.name,
      prediction: {
        riskLevel: "Unknown",
        probability: "N/A",
        status: "Insufficient Data",
        message:
          "Not enough historical monitoring data is available to predict database failure.",
        recommendations: [
          "Continue monitoring the database.",
          "Collect more historical monitoring data.",
        ],
      },
    });
  }

  /*
   * ==========================
   * CURRENT METRICS
   * ==========================
   */

  const latest = history[0];

  /*
   * ==========================
   * HISTORICAL AVERAGES
   * ==========================
   */

  const avgConnections = average(
    history,
    "activeConnections"
  );

  const avgRunningQueries = average(
    history,
    "runningQueries"
  );

  const avgSlowQueries = average(
    history,
    "slowQueries"
  );

  const avgDeadlocks = average(
    history,
    "deadlocks"
  );

  const avgLocks = average(
    history,
    "locks"
  );

  const avgLongTransactions = average(
    history,
    "longTransactions"
  );

  /*
   * ==========================
   * HISTORICAL MAXIMUMS
   * ==========================
   */

  const maxConnections = maximum(
    history,
    "activeConnections"
  );

  const maxRunningQueries = maximum(
    history,
    "runningQueries"
  );

  const maxSlowQueries = maximum(
    history,
    "slowQueries"
  );

  const maxDeadlocks = maximum(
    history,
    "deadlocks"
  );

  const maxLocks = maximum(
    history,
    "locks"
  );

  const maxLongTransactions = maximum(
    history,
    "longTransactions"
  );

  /*
   * ==========================
   * RISK SCORE
   * ==========================
   *
   * Maximum possible score = 100
   */

  let riskScore = 0;

  const recommendations = [];

  /*
   * 1. Health Score
   */

  const healthScore =
    latest.healthScore ??
    database.healthScore ??
    null;

  if (healthScore !== null) {
    if (healthScore < 40) {
      riskScore += 35;

      recommendations.push(
        "Database health is critically low. Immediate maintenance is recommended."
      );
    } else if (healthScore < 60) {
      riskScore += 25;

      recommendations.push(
        "Database health is below the safe range. Investigate performance issues."
      );
    } else if (healthScore < 80) {
      riskScore += 10;

      recommendations.push(
        "Database health is below optimal. Continue monitoring."
      );
    }
  }

  /*
   * 2. Active Connections
   *
   * Compare current connections against
   * historical average.
   */

  const currentConnections =
    Number(latest.activeConnections || 0);

  if (
    avgConnections > 0 &&
    currentConnections > avgConnections * 2
  ) {
    riskScore += 15;

    recommendations.push(
      "Active connections are significantly above the historical average."
    );
  } else if (
    avgConnections > 0 &&
    currentConnections > avgConnections * 1.5
  ) {
    riskScore += 8;

    recommendations.push(
      "Active connections are trending above normal levels."
    );
  }

  /*
   * 3. Running Queries
   */

  const currentRunningQueries =
    Number(latest.runningQueries || 0);

  if (
    avgRunningQueries > 0 &&
    currentRunningQueries >
      avgRunningQueries * 2
  ) {
    riskScore += 10;

    recommendations.push(
      "Running queries are significantly above the historical average."
    );
  }

  /*
   * 4. Slow Queries
   */

  const currentSlowQueries =
    Number(latest.slowQueries || 0);

  if (currentSlowQueries > 0) {
    riskScore += 10;

    recommendations.push(
      "Slow queries detected. Query optimization should be investigated."
    );
  }

  if (
    maxSlowQueries > 0 &&
    currentSlowQueries >= maxSlowQueries
  ) {
    riskScore += 5;
  }

  /*
   * 5. Deadlocks
   */

  const currentDeadlocks =
    Number(latest.deadlocks || 0);

  if (currentDeadlocks > 0) {
    riskScore += 15;

    recommendations.push(
      "Deadlocks detected. Investigate transaction and locking conflicts."
    );
  }

  /*
   * 6. Locks
   */

  const currentLocks =
    Number(latest.locks || 0);

  if (
    avgLocks > 0 &&
    currentLocks > avgLocks * 2
  ) {
    riskScore += 8;

    recommendations.push(
      "Lock activity is significantly above the historical average."
    );
  }

  /*
   * 7. Long Transactions
   */

  const currentLongTransactions =
    Number(latest.longTransactions || 0);

  if (currentLongTransactions > 0) {
    riskScore += 8;

    recommendations.push(
      "Long-running transactions detected."
    );
  }

  /*
   * 8. Database Size
   *
   * Do NOT compare the raw string.
   */

  const databaseSizeMB = parseDatabaseSize(
    latest.databaseSize ||
      database.databaseSize
  );

  /*
   * We only flag very large databases here.
   * Size itself is not automatically a failure.
   */

  if (databaseSizeMB > 10240) {
    riskScore += 8;

    recommendations.push(
      "Database size exceeds 10 GB. Review storage growth and archive unused data."
    );
  }

  /*
   * ==========================
   * TREND ANALYSIS
   * ==========================
   */

  const recentRecords = history.slice(0, 10);
  const olderRecords = history.slice(10, 20);

  if (
    recentRecords.length >= 3 &&
    olderRecords.length >= 3
  ) {
    const recentConnections = average(
      recentRecords,
      "activeConnections"
    );

    const olderConnections = average(
      olderRecords,
      "activeConnections"
    );

    /*
     * Detect meaningful increase.
     */

    if (
      olderConnections > 0 &&
      recentConnections >
        olderConnections * 1.5
    ) {
      riskScore += 10;

      recommendations.push(
        "Active connection usage is increasing compared with earlier monitoring periods."
      );
    }

    const recentSlowQueries = average(
      recentRecords,
      "slowQueries"
    );

    const olderSlowQueries = average(
      olderRecords,
      "slowQueries"
    );

    if (
      olderSlowQueries === 0 &&
      recentSlowQueries > 0
    ) {
      riskScore += 8;

      recommendations.push(
        "Slow query activity has recently appeared in monitoring data."
      );
    }
  }

  /*
   * ==========================
   * LIMIT SCORE
   * ==========================
   */

  riskScore = Math.min(
    Math.max(Math.round(riskScore), 0),
    100
  );

  /*
   * ==========================
   * RISK LEVEL
   * ==========================
   */

  let riskLevel = "Low";
  let status = "Healthy";
  let message =
    "Database is currently healthy based on recent monitoring data.";

  if (riskScore >= 70) {
    riskLevel = "High";
    status = "Critical";

    message =
      "Recent monitoring data indicates a high risk of future database performance or availability issues.";
  } else if (riskScore >= 40) {
    riskLevel = "Medium";
    status = "Warning";

    message =
      "Some monitoring indicators require attention. Continue monitoring the database closely.";
  } else if (riskScore >= 20) {
    riskLevel = "Low";
    status = "Healthy";

    message =
      "Database is generally healthy, but some performance indicators should be monitored.";
  }

  /*
   * If there are no problems, provide a
   * meaningful positive recommendation.
   */

  if (recommendations.length === 0) {
    recommendations.push(
      "Database is operating within the normal range.",
      "Continue monitoring historical performance trends."
    );
  }

  /*
   * ==========================
   * FINAL RESPONSE
   * ==========================
   */

  return okResult({
    success: true,

    database: database.name,

    prediction: {
      riskLevel,

      probability: `${riskScore}%`,

      status,

      message,

      recommendations,
    },

    analysis: {
      recordsAnalyzed: history.length,

      current: {
        activeConnections: currentConnections,
        runningQueries: currentRunningQueries,
        slowQueries: currentSlowQueries,
        deadlocks: currentDeadlocks,
        locks: currentLocks,
        longTransactions:
          currentLongTransactions,
        databaseSize:
          latest.databaseSize,
      },

      historical: {
        averageConnections:
          Number(avgConnections.toFixed(2)),

        maximumConnections:
          maxConnections,

        averageRunningQueries:
          Number(avgRunningQueries.toFixed(2)),

        maximumRunningQueries:
          maxRunningQueries,

        averageSlowQueries:
          Number(avgSlowQueries.toFixed(2)),

        maximumSlowQueries:
          maxSlowQueries,

        averageDeadlocks:
          Number(avgDeadlocks.toFixed(2)),

        maximumDeadlocks:
          maxDeadlocks,

        averageLocks:
          Number(avgLocks.toFixed(2)),

        maximumLocks:
          maxLocks,

        averageLongTransactions:
          Number(
            avgLongTransactions.toFixed(2)
          ),

        maximumLongTransactions:
          maxLongTransactions,
      },
    },
  });
}

module.exports = {
  predictDatabaseFailureService,
};